include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false #TODO remove on release
    prefer_single_quotes: true
analyzer:
  errors:
    non_constant_identifier_names: ignore
