name: phone_store
description: phone store.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.0
  image_picker_for_web: ^2.2.0
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  page_transition: ^2.0.9
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  simple_animations: ^5.0.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OpenSans_Condensed
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Bold.ttf
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
        - asset: assets/fonts/OpenSans_Condensed-Regular.ttf
        - asset: assets/fonts/OpenSans_Condensed-Semibold.ttf
