// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1VTeiARvajJKZS4NRp6zNQPb8SlHoH4A',
    appId: '1:366249433376:web:1f87e63b1d0920914c1f45',
    messagingSenderId: '366249433376',
    projectId: 'mobile-store-475a0',
    authDomain: 'mobile-store-475a0.firebaseapp.com',
    storageBucket: 'mobile-store-475a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADV2Y8tfLpaJUtXdI8vN3Nm1Qz3BCuxPI',
    appId: '1:366249433376:android:f0e5b0540c428cc44c1f45',
    messagingSenderId: '366249433376',
    projectId: 'mobile-store-475a0',
    storageBucket: 'mobile-store-475a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbGT8h58B2czDV8caPe1njbBEykn4pxc',
    appId: '1:366249433376:ios:5e98eb6fae0f6b4c4c1f45',
    messagingSenderId: '366249433376',
    projectId: 'mobile-store-475a0',
    storageBucket: 'mobile-store-475a0.appspot.com',
    iosClientId: '366249433376-2tnrtgl2mov88eer8lm8244u8a7tko0i.apps.googleusercontent.com',
    iosBundleId: 'com.kurmantaev.mobilestore',
  );
}
